[package]
name = "cargo-ci-template"
version = "0.4.64"
edition = "2021"
rust-version = "1.74.0"
authors = ["Lin Rongbin <linrongbin16@outlook.com>"]
description = "Cargo CI template."
repository = "https://github.com/linrongbin16/cargo-ci-template.rs"
readme = "README.md"
homepage = "https://github.com/linrongbin16/cargo-ci-template.rs"
documentation = "https://docs.rs/cargo-ci-template.rs"
license = "GPL-3.0"
keywords = ["cargo", "ci"]

[dependencies]
crossterm = { version = "0.28", features = ["event-stream"] }
heed = "0.20.5"
v8 = "0.106.0"

[profile.release]
lto = "thin"

[profile.nightly]
inherits = "release"
debug = true
