[package]
name = "cargo-ci-template"
version = "0.4.64"
edition = "2021"
rust-version = "1.74.0"
authors = ["Lin Rongbin <linrongbin16@outlook.com>"]
description = "Cargo CI template."
repository = "https://github.com/linrongbin16/cargo-ci-template.rs"
readme = "README.md"
homepage = "https://github.com/linrongbin16/cargo-ci-template.rs"
documentation = "https://docs.rs/cargo-ci-template.rs"
license = "GPL-3.0"
keywords = ["cargo", "ci"]

[dependencies]
crossterm = { version = "0.27", features = ["event-stream"] }
cargo-dependabot-test = "0.5"
heed = "0.20.2"
tempfile = "3"

[profile.release]
lto = "thin"

[profile.nightly]
inherits = "release"
debug = true
