allow-branch = ["main"]
pre-release-hook = ["git-cliff", "--latest", "--tag", "{{version}}"]
tag-message = "chore(release): {{version}}"
tag-name = "v{{version}}"
pre-release-commit-message = "chore(release): {{version}}"
shared-version = true
release = true
tag = true
