name: Manual Nightly Build
permissions:
  contents: write
on:
  schedule:
    - cron: "0 0 * * 1"
  workflow_dispatch:
env:
  CARGO_INCREMENTAL: 0
  CARGO_NET_GIT_FETCH_WITH_CLI: true
  CARGO_NET_RETRY: 10
  CARGO_TERM_COLOR: always
  RUST_BACKTRACE: 1
  RUSTFLAGS: -D warnings
  RUSTUP_MAX_RETRIES: 10
defaults:
  run:
    shell: bash
jobs:
  delete-release:
    name: Delete Release
    runs-on: ubuntu-latest
    steps:
      - uses: dev-drprasad/delete-tag-and-release@v1.1
        with:
          tag_name: nightly
          github_token: ${{ secrets.GITHUB_TOKEN }}
  prepare-release:
    name: Prepare Release
    runs-on: ubuntu-latest
    needs: delete-release
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: dtolnay/rust-toolchain@stable
      - uses: Swatinem/rust-cache@v2
      - name: Create Changelog
        run: |
          cargo install git-cliff --all-features
          git-cliff -u --verbose -o UPDATES.md
      - uses: ncipollo/release-action@v1
        with:
          allowUpdates: true
          prerelease: true
          makeLatest: true
          name: "Nightly Build"
          bodyFile: UPDATES.md
          removeArtifacts: true
          tag: nightly
          commit: main
  upload-assets:
    name: ${{ matrix.target }}
    runs-on: ${{ matrix.os }}
    needs: prepare-release
    strategy:
      matrix:
        include:
          - target: aarch64-unknown-linux-gnu
            os: ubuntu-22.04
            v8_from_source: false
          # - target: aarch64-unknown-linux-musl
          #   os: ubuntu-22.04
          - target: aarch64-apple-darwin
            os: macos-13
            v8_from_source: false
          - target: aarch64-pc-windows-msvc
            os: windows-2022
            v8_from_source: true
          - target: x86_64-unknown-linux-gnu
            os: ubuntu-22.04
            v8_from_source: false
          # - target: x86_64-unknown-linux-musl
          #   os: ubuntu-22.04
          - target: x86_64-apple-darwin
            os: macos-13
            v8_from_source: false
          - target: x86_64-pc-windows-msvc
            os: windows-2022
            v8_from_source: false
          - target: x86_64-unknown-freebsd
            os: ubuntu-22.04
            v8_from_source: true
    timeout-minutes: 60
    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@stable
      - uses: taiki-e/setup-cross-toolchain-action@v1
        with:
          target: ${{ matrix.target }}
        if: startsWith(matrix.os, 'ubuntu')
      - run: sudo apt-get install -y libglib2.0-dev curl python3
        if: startsWith(matrix.os, 'ubuntu')
      - uses: taiki-e/install-action@cross
        if: contains(matrix.target, '-musl')
      - run: echo "RUSTFLAGS=${RUSTFLAGS} -C target-feature=+crt-static" >> "${GITHUB_ENV}"
        if: endsWith(matrix.target, 'windows-msvc')
      - run: echo "V8_FROM_SOURCE=1" >> "${GITHUB_ENV}"
        if: ${{ matrix.v8_from_source }}
      - uses: taiki-e/upload-rust-binary-action@v1
        with:
          archive: ${{ format('cargo-ci-template-{0}', matrix.target) }}
          bin: cargo-ci-template,hello,cargo-ci-template1,cargo-ci-template2,cargo-ci
          target: ${{ matrix.target }}
          tar: all
          zip: windows
          token: ${{ secrets.GITHUB_TOKEN }}
          include: README.md,LICENSE
          checksum: sha256
          ref: refs/tags/nightly
          profile: nightly
      - name: After Build
        run: |
          echo "ls -lah --color=always"
          ls -lah --color=always
      - run: cargo build
